sudo: required

language: ruby
rvm:
  - 2.3.1

env:
  global:
  - TRAVIS_NODE_VERSION="v7.1.0"
  - STAGING_BRANCH=dev
  - PRODUCTION_BRANCH=master
before_install:
  - sudo chmod +x ./.build_scripts/build.sh
  - suod chmod +x ./.build_scripts/deploy.sh
install:
  - sudo . $HOME/.nvm/nvm.sh
  - sudo nvm install $TRAVIS_NODE_VERSION
  - sudo nvm use $TRAVIS_NODE_VERSION
  - sudo npm install
script:
  - sudo npm test
  - sudo ./.build_scripts/build.sh
deploy:
  - provider: s3
    access_key_id: ${ACCESS_KEY_ID}
    secret_access_key: ${SECRET_ACCESS_KEY}
    bucket: mm-microsites-staging
    local_dir: './_site/'
    skip_cleanup: true
    on:
      branch: ${STAGING_BRANCH}
  - provider: script
    skip_cleanup: true
    script: "sudo .build_scripts/deploy.sh"
    on:
      branch: "${PRODUCTION_BRANCH}"
