sudo: false

language: ruby
rvm:
  - 2.3.1

env:
  global:
  - TRAVIS_NODE_VERSION="v7.1.0"
  - STAGING_BRANCH=dev
  - PRODUCTION_BRANCH=master
before_install:
  - free -m
  - chmod +x ./.build_scripts/build.sh
  - chmod +x ./.build_scripts/deploy.sh
install:
  - free -m
  - $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install
  - free -m
script:
  - npm test
  - free -m
  - ./.build_scripts/build.sh
  - free -m
deploy:
  - provider: s3
    access_key_id: ${ACCESS_KEY_ID}
    secret_access_key: ${SECRET_ACCESS_KEY}
    bucket: mm-microsites-staging
    local_dir: './_site/'
    skip_cleanup: true
    on:
      branch: ${STAGING_BRANCH}
  - provider: script
    skip_cleanup: true
    script: ".build_scripts/deploy.sh"
    on:
      branch: "${PRODUCTION_BRANCH}"
