safe: false
source: app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md

timezone: America/New_York
highlighter: false

domain: https://www.missingmaps.org
# if doing local dev, comment out path_prefix
path_prefix: /microsites

default_microsite: all

collections:
  country:
    output: true
    permalink: /:path/
    lang: en
  updates:
    output: true
    permalink: /:path/
