# Site settings
title: mm-microsite
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

domain:         http://www.missingmaps.org
path_prefix:    /microsites

default_microsite: all

collections:
  country:
    output: true
    permalink: /:path/
    lang: en
